### ISSUE TITLE
Permissions errors

### ISSUE THREAD

**Issue by simonzack** [rumpelsepp/gitlab-pkgbuilds#6]
I'm getting a lot of these on installing gitlab:
    
    warning: directory ownership differs on /usr/share/webapps/gitlab/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/www/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/vendor/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/spec/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/public/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/lib/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/features/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/docker/
    filesystem: 1001:1002  package: 0:0
    warning: directory ownership differs on /usr/share/webapps/gitlab/doc/
    ...

**Comment by rumpelsepp** [comment]
Did you build your package as root?

**Comment by simonzack** [comment]
I don't think so, I did a `yaourt -S gitlab` to install the package.

**Comment by rumpelsepp** [comment]
Currently I have no idea. I updated my setup yesterday and it worked well. I will do a few more tests tomorrow.

**Comment by rumpelsepp** [comment]
Ah. Wait a moment. You said you used `yaourt`? My package build differs from the aur. I have developed it with @hunger and the AUR maintainer just adopted our changes partially. So as a first try, try building it manually. I will update the PKGBUILDs to the most recent release tomorrow. Basically you only have to increment the version number and remove [these patches](https://github.com/rumpelsepp/gitlab-pkgbuilds/blob/master/gitlab/PKGBUILD#L44-L45) (they are already included upstream).

**Comment by rumpelsepp** [comment]
There are probably some changes in pacman 4.2 which cause these warnings. The ownerships are fixed in the install script. I am wondering what is the correct way to do it as the UID could differ between systems...

**Comment by rumpelsepp** [comment]
Closing this one. This is a pacman "issue", see here:

* https://lists.archlinux.org/pipermail/pacman-dev/2015-February/019880.html
* https://lists.archlinux.org/pipermail/pacman-dev/2015-February/019879.html
